### ISSUE TITLE
Wrong display for transformed Picster text elements

### ISSUE THREAD

**Issue by jamesthcheung** [HfMT-ZM4/MaxScore#62]
Texts are rendered at a wrong position for transforms like "matrix(0.5, 0, 0, 0.5, 0, 0)". Everything else is correct

**Comment by computermusik** [comment]
This is due to a bug in the JUCE implementation of SVG. You'd have to use a factor for each element instead.

**Comment by jamesthcheung** [comment]
Just tried setting the transform matrix inside individual elements in the group, but the problem seems to persist... or did I misunderstand?

**Comment by computermusik** [comment]
What I meant is that the factor has to be applied to to x and y, width and height not just to the individual transform as this also is affected by the JUCE bug.
