### ISSUE TITLE
live expression editor

### ISSUE THREAD

**Issue by jamesthcheung** [HfMT-ZM4/MaxScore#90]

**Comment by computermusik** [comment]
Review formatting of messages: bpf has an empty space after the f: "bpf ". 
There are still some messages printing to the console

**Comment by jamesthcheung** [comment]
Fixed

**Comment by computermusik** [comment]
Ableton Params are all between 0 and 1.  We need to add a mechanism that maps the actual param range to 0 - 1.
Currently, the curve is too thick, because of a wrong transform value. Let's have a conversation about this soon!

**Comment by jamesthcheung** [comment]
To do list:
- fix thickness issue for bpf (scale the value not transform)
- investigate ej.function.js & email emmanuel@cycling74.com (can output current x, y?)
- display current point dynamically with call_str_something
- Get note length / other values to determine bpf duration

**Comment by computermusik** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/17442406/112998659-8c3a6780-916e-11eb-9e3a-b149c737a92c.png">
You can probably do this without ej.function: Just use pattr and create a js function capable of outputting the part of an array that changes. You can probably do this in less than 30 minutes.

**Comment by computermusik** [comment]
this is also useful:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/17442406/112999295-1aaee900-916f-11eb-834d-77736ffb197d.png">

**Comment by jamesthcheung** [comment]
Wow, this mousereport attribute is exactly what we were looking for. Great!! That's easy then

**Comment by computermusik** [comment]
I was wrong about the param range of a Live device param. They can also be outside of 0 - 1. The values are automatically given by Device.SelectParameter when a new param is selected. See image.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/17442406/113150417-58297a00-9234-11eb-9228-22d5340c0d06.png">

**Comment by jamesthcheung** [comment]
live.expr should be done ;) Please check if everything's ok
